### ISSUE TITLE
Can't get more than 2 DS3 controllers to Pair

### ISSUE THREAD

**Issue by elsonrodriguez** [ProfessorKaos64/RetroRig-ES#16]
After pairing two controllers, I can only pair additional controllers if I turn one of the paired ones off.

I'd be happy to run commands or provide output from my setup.

**Comment by mdeguzis** [comment]
hmmm odd, i'll try to check this out this week. Thanks!

**Comment by elsonrodriguez** [comment]
This turned out to be a hardware issue with an Intel NUC (DC53427HYE).

The built-in bluetooth can only pair with 2 PS3 controllers. I plugged in a 2nd USB Bluetooth dongle and it paired 3 additional controllers.

Not a bug.

**Comment by mdeguzis** [comment]
Ok, thank you for the update @elsonrodriguez
