### ISSUE TITLE
Installation will not start.

### ISSUE THREAD

**Issue by Lockzi** [ProfessorKaos64/RetroRig-ES#4]
administrator@TV-PC:~/RetroRig-ES$ sudo ./retrorig-es-setup
###### 

Loading script modules
###### 

Loaded module helpers.shinc
Loaded module configuration.shinc
Loaded module settings.shinc
Loaded module setup.shinc
Loaded module gamepads.shinc
Loaded module emulators.shinc
Loaded module emulators-source.shinc
###### 

Checking compatibility
###### 

64-bit
Setting syscalls based on default package manager...
/home/administrator/RetroRig-ES/scriptmodules/setup.shinc: line 435: /home/administrator/RetroRig-ES/scriptmodules/syscalls-debian.shinc: No such file or directory
Supported Platform? Yes
Distro: Ubuntu
Release: 14.04
Default init system: upstart
Primary package management system: apt/aptitude
###### 
###### 

Pre-req checks
###### 

Did not find 1 or more of the packages: git, dialog, or figlet
Attempting to install these now.

git: 'dialog' is not a git command. See 'git --help'.

**Comment by Lockzi** [comment]
Solved by:

mv ~/RetroRig-ES/scriptmodules/syscalls-debian ~/RetroRig-ES/scriptmodules/syscalls-debian.shinc

The file was missing .shinc extension

**Comment by mdeguzis** [comment]
This is easy enough to fix. I'll get this tonight for you. Stand by

On January 8, 2015 2:37:04 PM EST, Lockzi notifications@github.com wrote:

> administrator@TV-PC:~/RetroRig-ES$ sudo ./retrorig-es-setup
> #####################################################
> Loading script modules
> #####################################################
> Loaded module helpers.shinc
> Loaded module configuration.shinc
> Loaded module settings.shinc
> Loaded module setup.shinc
> Loaded module gamepads.shinc
> Loaded module emulators.shinc
> Loaded module emulators-source.shinc
> #####################################################
> Checking compatibility
> #####################################################
> 64-bit
> Setting syscalls based on default package manager...
> /home/administrator/RetroRig-ES/scriptmodules/setup.shinc: line 435:
> /home/administrator/RetroRig-ES/scriptmodules/syscalls-debian.shinc: No
> such file or directory
> Supported Platform? Yes
> Distro: Ubuntu
> Release: 14.04
> Default init system: upstart
> Primary package management system: apt/aptitude
> #####################################################
> 
> ######################################
> Pre-req checks
> ######################################
> Did not find 1 or more of the packages: git, dialog, or figlet
> Attempting to install these now.
> 
> git: 'dialog' is not a git command. See 'git --help'.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ProfessorKaos64/RetroRig-ES/issues/4

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mdeguzis** [comment]
Awesome.. Sorry for that. I was doing a lot of work yesterday. I should set up the staging or beta branch soon for testing. I'm busy trying to plan arch Linux and build utopic packages. 

On January 8, 2015 2:40:00 PM EST, Lockzi notifications@github.com wrote:

> Solved by:
> 
> mv ~/RetroRig-ES/scriptmodules/syscalls-debian
> ~/RetroRig-ES/scriptmodules/syscalls-debian.shinc
> 
> The file was missing .shinc extension
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ProfessorKaos64/RetroRig-ES/issues/4#issuecomment-69236071

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mdeguzis** [comment]
Should be fixed with commit bed5776. Thank you @lockzi. I'm writing this from the road, so check that things are OK and I'll close this.
