### ISSUE TITLE
Start RetroRig-ES when PS3 controller turns on

### ISSUE THREAD

**Issue by Lockzi** [ProfessorKaos64/RetroRig-ES#7]
When installing you rapidly see an error about XBMC something after answering YES if it should start when first PS3 controller turns on.

That shouldn't be there on an ES install ;)

**Comment by mdeguzis** [comment]
@Lockzi , lots\* of code updates today (added Nintendo DS support). That is one thing I either need to remove or fix up for Emulationstation. Thanks for submitting this so I don't forget! :)

Update, just tested hotplugging. Works fine (without that code that doesn't work anyway), there are some other things that I need to cleanup. Don't worry, more legacy code fixes/removals coming.

**Comment by mdeguzis** [comment]
@Lockzi I just amended the gp_autodetect() function and rescan service with commit 70c4c30. I tested it by doing a fresh install. ES should now load on a fresh install, if closed, and the PS button is pressed. Other syntax errors I will find in my test log that I piped the setup to. Fixes from that will come over the next few days.

Please reinstall and test. You should not need to backup your ROMs or saves, but I would do so in case you have started playing anything. Better safe than sorry. Fail-safe catches with that kind of stuff are there, but are likely not 100% perfect.

-PK
